/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ch.epfl.eagle.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-03")
public class TNodeState implements org.apache.thrift.TBase<TNodeState, TNodeState._Fields>, java.io.Serializable, Cloneable, Comparable<TNodeState> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TNodeState");

  private static final org.apache.thrift.protocol.TField EAGLE_USAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("eagleUsage", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField EXTERNAL_USAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("externalUsage", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TNodeStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TNodeStateTupleSchemeFactory());
  }

  public TResourceVector eagleUsage; // required
  public TResourceVector externalUsage; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EAGLE_USAGE((short)1, "eagleUsage"),
    EXTERNAL_USAGE((short)2, "externalUsage");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EAGLE_USAGE
          return EAGLE_USAGE;
        case 2: // EXTERNAL_USAGE
          return EXTERNAL_USAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EAGLE_USAGE, new org.apache.thrift.meta_data.FieldMetaData("eagleUsage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TResourceVector.class)));
    tmpMap.put(_Fields.EXTERNAL_USAGE, new org.apache.thrift.meta_data.FieldMetaData("externalUsage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TResourceVector.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TNodeState.class, metaDataMap);
  }

  public TNodeState() {
  }

  public TNodeState(
    TResourceVector eagleUsage,
    TResourceVector externalUsage)
  {
    this();
    this.eagleUsage = eagleUsage;
    this.externalUsage = externalUsage;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TNodeState(TNodeState other) {
    if (other.isSetEagleUsage()) {
      this.eagleUsage = new TResourceVector(other.eagleUsage);
    }
    if (other.isSetExternalUsage()) {
      this.externalUsage = new TResourceVector(other.externalUsage);
    }
  }

  public TNodeState deepCopy() {
    return new TNodeState(this);
  }

  @Override
  public void clear() {
    this.eagleUsage = null;
    this.externalUsage = null;
  }

  public TResourceVector getEagleUsage() {
    return this.eagleUsage;
  }

  public TNodeState setEagleUsage(TResourceVector eagleUsage) {
    this.eagleUsage = eagleUsage;
    return this;
  }

  public void unsetEagleUsage() {
    this.eagleUsage = null;
  }

  /** Returns true if field eagleUsage is set (has been assigned a value) and false otherwise */
  public boolean isSetEagleUsage() {
    return this.eagleUsage != null;
  }

  public void setEagleUsageIsSet(boolean value) {
    if (!value) {
      this.eagleUsage = null;
    }
  }

  public TResourceVector getExternalUsage() {
    return this.externalUsage;
  }

  public TNodeState setExternalUsage(TResourceVector externalUsage) {
    this.externalUsage = externalUsage;
    return this;
  }

  public void unsetExternalUsage() {
    this.externalUsage = null;
  }

  /** Returns true if field externalUsage is set (has been assigned a value) and false otherwise */
  public boolean isSetExternalUsage() {
    return this.externalUsage != null;
  }

  public void setExternalUsageIsSet(boolean value) {
    if (!value) {
      this.externalUsage = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EAGLE_USAGE:
      if (value == null) {
        unsetEagleUsage();
      } else {
        setEagleUsage((TResourceVector)value);
      }
      break;

    case EXTERNAL_USAGE:
      if (value == null) {
        unsetExternalUsage();
      } else {
        setExternalUsage((TResourceVector)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EAGLE_USAGE:
      return getEagleUsage();

    case EXTERNAL_USAGE:
      return getExternalUsage();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EAGLE_USAGE:
      return isSetEagleUsage();
    case EXTERNAL_USAGE:
      return isSetExternalUsage();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TNodeState)
      return this.equals((TNodeState)that);
    return false;
  }

  public boolean equals(TNodeState that) {
    if (that == null)
      return false;

    boolean this_present_eagleUsage = true && this.isSetEagleUsage();
    boolean that_present_eagleUsage = true && that.isSetEagleUsage();
    if (this_present_eagleUsage || that_present_eagleUsage) {
      if (!(this_present_eagleUsage && that_present_eagleUsage))
        return false;
      if (!this.eagleUsage.equals(that.eagleUsage))
        return false;
    }

    boolean this_present_externalUsage = true && this.isSetExternalUsage();
    boolean that_present_externalUsage = true && that.isSetExternalUsage();
    if (this_present_externalUsage || that_present_externalUsage) {
      if (!(this_present_externalUsage && that_present_externalUsage))
        return false;
      if (!this.externalUsage.equals(that.externalUsage))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_eagleUsage = true && (isSetEagleUsage());
    list.add(present_eagleUsage);
    if (present_eagleUsage)
      list.add(eagleUsage);

    boolean present_externalUsage = true && (isSetExternalUsage());
    list.add(present_externalUsage);
    if (present_externalUsage)
      list.add(externalUsage);

    return list.hashCode();
  }

  @Override
  public int compareTo(TNodeState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEagleUsage()).compareTo(other.isSetEagleUsage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEagleUsage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eagleUsage, other.eagleUsage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExternalUsage()).compareTo(other.isSetExternalUsage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternalUsage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externalUsage, other.externalUsage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TNodeState(");
    boolean first = true;

    sb.append("eagleUsage:");
    if (this.eagleUsage == null) {
      sb.append("null");
    } else {
      sb.append(this.eagleUsage);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("externalUsage:");
    if (this.externalUsage == null) {
      sb.append("null");
    } else {
      sb.append(this.externalUsage);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (eagleUsage != null) {
      eagleUsage.validate();
    }
    if (externalUsage != null) {
      externalUsage.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TNodeStateStandardSchemeFactory implements SchemeFactory {
    public TNodeStateStandardScheme getScheme() {
      return new TNodeStateStandardScheme();
    }
  }

  private static class TNodeStateStandardScheme extends StandardScheme<TNodeState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TNodeState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EAGLE_USAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.eagleUsage = new TResourceVector();
              struct.eagleUsage.read(iprot);
              struct.setEagleUsageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EXTERNAL_USAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.externalUsage = new TResourceVector();
              struct.externalUsage.read(iprot);
              struct.setExternalUsageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TNodeState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.eagleUsage != null) {
        oprot.writeFieldBegin(EAGLE_USAGE_FIELD_DESC);
        struct.eagleUsage.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.externalUsage != null) {
        oprot.writeFieldBegin(EXTERNAL_USAGE_FIELD_DESC);
        struct.externalUsage.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TNodeStateTupleSchemeFactory implements SchemeFactory {
    public TNodeStateTupleScheme getScheme() {
      return new TNodeStateTupleScheme();
    }
  }

  private static class TNodeStateTupleScheme extends TupleScheme<TNodeState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TNodeState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEagleUsage()) {
        optionals.set(0);
      }
      if (struct.isSetExternalUsage()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetEagleUsage()) {
        struct.eagleUsage.write(oprot);
      }
      if (struct.isSetExternalUsage()) {
        struct.externalUsage.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TNodeState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.eagleUsage = new TResourceVector();
        struct.eagleUsage.read(iprot);
        struct.setEagleUsageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.externalUsage = new TResourceVector();
        struct.externalUsage.read(iprot);
        struct.setExternalUsageIsSet(true);
      }
    }
  }

}

